name: Test_1

"on":
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
      region:
        description: "Select region"
        required: true

jobs:
  practice:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Region: ${{ github.event.inputs.region }}"

      - name: Verify secret
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
        run: |
          echo "Secret is configured"
